import type { Prisma } from "@prisma/client";

/** Keys that store CMS JSON (hero stays on home_hero_banners). */
export const HOME_BLOCK_KEYS = [
  "welcome_modal",
  "featured",
  "deals_banner",
  "product_groups",
  "promo_slider",
  "best_sellers",
  "latest_products",
  "deals_of_day",
  "laptop_repair",
  "top_brands",
] as const;

export type HomeBlockKey = (typeof HOME_BLOCK_KEYS)[number];

export const DEFAULT_HOME_BLOCKS: Record<
  HomeBlockKey,
  Prisma.InputJsonValue
> = {
  welcome_modal: {
    badge_label: "Limited Offer",
    eyebrow: "Don't Miss Out",
    headline_before: "Get Up To",
    discount_percent: 70,
    headline_after: "Off Digital Cameras",
    body: "Flash deal ends when the timer hits zero. Shop now before this offer disappears.",
    cta_label: "Shop Now",
    cta_href: "/shop?category=cameras",
    dismiss_label: "No thanks, close",
    countdown_seconds: 30,
    product_image: "/images/camera.png",
    bg_image: "/images/hero_bg_06 1.png",
  },
  featured: {
    items: [
      {
        title: "Free Shipping",
        description: "Free shipping on all your order",
        icon: "/icons/featured_delivery-truck 1.svg",
        alt: "Delivery Truck Icon",
      },
      {
        title: "Customer Support 24/7",
        description: "Instant access to Support",
        icon: "/icons/featured_Group.svg",
        alt: "Headset Support Icon",
      },
      {
        title: "100% Secure Payment",
        description: "We ensure your money is safe",
        icon: "/icons/featured_Group-1.svg",
        alt: "Secure Bag Icon",
      },
      {
        title: "Money-Back Guarantee",
        description: "30 Days Money-Back Guarantee",
        icon: "/icons/featured_Group-2.svg",
        alt: "Guarantee Package Box Icon",
      },
    ],
  },
  deals_banner: {
    cards: [
      {
        title_top: "BREAK DISC",
        title_bottom: "DEALS ON THIS",
        discount_percent: 70,
        image: "/images/products_group (1).jpg",
        alt: "Convertible Laptop Deal",
        href: "/shop?category=laptops",
        cta_label: "Shop Now",
      },
      {
        title_top: "BREAK DISC",
        title_bottom: "DEALS ON THIS",
        discount_percent: 70,
        image: "/images/top_products (2).png",
        alt: "Headphones and Smartphone Deal",
        href: "/shop?category=audio",
        cta_label: "Shop Now",
      },
      {
        title_top: "BREAK DISC",
        title_bottom: "DEALS ON THIS",
        discount_percent: 70,
        image: "/images/top_products (3).png",
        alt: "Tablet Device Deal",
        href: "/shop?category=tablets",
        cta_label: "Shop Now",
      },
      {
        title_top: "BREAK DISC",
        title_bottom: "DEALS ON THIS",
        discount_percent: 70,
        image: "/images/top_products (4).png",
        alt: "Curved Smart TV Deal",
        href: "/shop?category=televisions",
        cta_label: "Shop Now",
      },
    ],
  },
  product_groups: {
    title: "Product groups",
    note: "Layout chrome — product tiles still use section defaults until catalog sources are wired.",
  },
  promo_slider: {
    bg_image: "/images/PromoBannerSlider_bg.png",
    autoplay_ms: 4500,
    slides: [
      {
        price: "৳23,640",
        tagline: "ALL-NEW-SPORT",
        highlight_text: "5K",
        sub_highlight: "STARTING AT",
        category_tag: "OS Tablet",
        title_line1: "Acer Chromebook Tab",
        title_line2: "10 Is Official",
        cta_label: "SHOP NOW",
        cta_href: "/shop?product=acer-chromebook-tab-10",
        image: "/images/PromoBannerSlider_Product_1.png",
        image_alt: "Acer Chromebook Tab 10",
      },
      {
        price: "৳35,999",
        tagline: "PRO WORKSPACE",
        highlight_text: "4K",
        sub_highlight: "STARTING AT",
        category_tag: "IPS Monitor",
        title_line1: "Curved UltraWide",
        title_line2: "Display Edition",
        cta_label: "EXPLORE DEALS",
        cta_href: "/shop?product=curved-display-edition",
        image: "/images/PromoBannerSlider_Product_1.png",
        image_alt: "Curved UltraWide Monitor",
      },
      {
        price: "৳54,000",
        tagline: "ULTRA POWER",
        highlight_text: "12th",
        sub_highlight: "GEN INTEL",
        category_tag: "Touch Laptop",
        title_line1: "Convertible Yoga",
        title_line2: "Slim Pro Series",
        cta_label: "VIEW PRODUCT",
        cta_href: "/shop?product=yoga-slim-pro",
        image: "/images/PromoBannerSlider_Product_1.png",
        image_alt: "Convertible Touch Laptop",
      },
    ],
  },
  best_sellers: {
    title: "Best Sellers",
    promo_badge: "Hot Deal",
    promo_headline: "Engine Parts Collection",
    promo_discount_percent: 70,
    promo_cta_label: "Shop Now",
    promo_cta_href: "/shop",
    promo_image: "/images/best_seller_product_banner_poset_image.png",
    product_sort: "newest",
    product_limit: 8,
  },
  latest_products: {
    title: "Best Seller Product",
    sidebar_title: "Latest Items",
    product_sort: "newest",
    product_limit: 8,
    sidebar_limit: 6,
  },
  deals_of_day: {
    title: "Deals of the Day",
    left_badge: "Special Offer",
    left_headline: "Save Big Today",
    left_cta_label: "Shop Now",
    left_cta_href: "/shop",
    left_image: "/images/Deals of The Day left product image.png",
    left_bg: "/images/Deals of The Day_left_bg.jpg",
    product_sort: "newest",
    product_limit: 4,
  },
  laptop_repair: {
    badge_label: "Expert Mechanic",
    headline_line1: "Repair Laptop Perfectly",
    headline_line2: "From Expertist",
    subtext: "Sumptuous, filling, and temptingly",
    offer_percent: 30,
    offer_label: "offer",
    cta_label: "MAKE ENQUIRY",
    cta_href: "/contact?service=laptop-repair",
    bg_image: "/images/ad_promation_bg_bottom.jpg",
    product_image: "/images/ad_promation_product_imagesjpg.png",
  },
  top_brands: {
    title: "Top Brands",
    see_all_label: "See All Brands",
    see_all_href: "/brands",
    brands: [
      {
        name: "Apple",
        href: "/shop?brand=apple",
        image: "/images/apple.png",
      },
      { name: "Microsoft", href: "/shop?brand=microsoft", image: null },
      { name: "HP", href: "/shop?brand=hp", image: null },
      { name: "ASUS", href: "/shop?brand=asus", image: null },
      { name: "DELL", href: "/shop?brand=dell", image: null },
      { name: "Lenovo", href: "/shop?brand=lenovo", image: null },
      { name: "Acer", href: "/shop?brand=acer", image: null },
    ],
  },
};
