import type { ShopProduct } from "./types";

export const PRICE_RANGE = { min: 10, max: 110 } as const;

export const SHOP_COLORS = [
    { id: "green", value: "#00B207", label: "Green" },
    { id: "red", value: "#EA4B48", label: "Red" },
    { id: "blue", value: "#2388FF", label: "Blue" },
    { id: "orange", value: "#FF8A00", label: "Orange" },
    { id: "black", value: "#1A1A1A", label: "Black" },
    { id: "yellow", value: "#FFC107", label: "Yellow" },
    { id: "purple", value: "#7B61FF", label: "Purple" },
    { id: "pink", value: "#FF6B9D", label: "Pink" },
] as const;

export const SHOP_CATEGORIES = [
    { id: "laptops", label: "Laptops", count: 12 },
    { id: "desktop", label: "Desktop and Server", count: 8 },
    { id: "gaming", label: "Gaming", count: 15 },
    { id: "monitor", label: "Monitor", count: 9 },
    { id: "tablet", label: "Tablet PC", count: 11 },
    { id: "printer", label: "Printer", count: 6 },
    { id: "camera", label: "Camera", count: 10 },
] as const;

export const SHOP_BRANDS = [
    { id: "samsung", label: "Samsung", count: 14 },
    { id: "apple", label: "Apple", count: 9 },
    { id: "dell", label: "Dell", count: 11 },
    { id: "lenovo", label: "Lenovo", count: 8 },
    { id: "msi", label: "MSI", count: 7 },
    { id: "asus", label: "Asus", count: 10 },
] as const;

export const SHOP_TAGS = [
    "Symphony",
    "Nokia",
    "Oppo",
    "Landing Page",
    "Samsung",
    "iPhone 13 Pro Max",
    "Huawei",
    "iPhone 12",
    "Laptop",
    "Headphone",
] as const;

export const SORT_OPTIONS = [
    { value: "default", label: "Default Sorting" },
    { value: "price-asc", label: "Price: Low to High" },
    { value: "price-desc", label: "Price: High to Low" },
    { value: "name-asc", label: "Name: A to Z" },
    { value: "rating-desc", label: "Average Rating" },
] as const;

export const PRODUCTS_PER_PAGE = 12;

export const shopProducts: ShopProduct[] = [
    {
        id: 1,
        name: 'SAMSUNG Galaxy A7 Lite 8.7" 32GB Android Tablet',
        image: "/images/best_seller_product (1).png",
        alt: "Samsung Galaxy A7 Lite Tablet",
        rating: 4,
        reviewCount: 230,
        priceMin: 30.52,
        priceMax: 40.52,
        available: 994,
        isNew: true,
        category: "tablet",
        brand: "samsung",
        colors: ["black", "blue"],
        tags: ["Samsung", "Landing Page"],
    },
    {
        id: 2,
        name: "All-in-One Desktop PC with UltraWide Display",
        image: "/images/Best Seller Product anather (1).png",
        alt: "All-in-One Desktop PC",
        rating: 5,
        reviewCount: 182,
        priceMin: 39.52,
        priceMax: 49.52,
        available: 354,
        isNew: true,
        category: "desktop",
        brand: "dell",
        colors: ["black", "silver"],
        tags: ["Laptop", "Landing Page"],
    },
    {
        id: 3,
        name: "HP DeskJet 4255e Wireless All-in-One Printer",
        image: "/images/best_seller_product (2).png",
        alt: "HP DeskJet Wireless Printer",
        rating: 4,
        reviewCount: 96,
        priceMin: 45.0,
        priceMax: 55.0,
        available: 210,
        isNew: true,
        category: "printer",
        brand: "dell",
        colors: ["black", "white"],
        tags: ["Laptop", "Landing Page"],
    },
    {
        id: 4,
        name: "Optoma UHZ35ST Ultra Short Throw 4K Projector",
        image: "/images/best_seller_product (3).png",
        alt: "Optoma UHZ35ST Projector",
        rating: 4,
        reviewCount: 64,
        priceMin: 52.0,
        priceMax: 68.0,
        available: 88,
        isNew: true,
        category: "monitor",
        brand: "asus",
        colors: ["black"],
        tags: ["Headphone"],
    },
    {
        id: 5,
        name: "Canon EOS Rebel T7 DSLR Camera with Lens Kit",
        image: "/images/best_seller_product (4).png",
        alt: "Canon EOS Rebel T7 Camera",
        rating: 5,
        reviewCount: 311,
        priceMin: 48.5,
        priceMax: 62.0,
        available: 142,
        isNew: true,
        category: "camera",
        brand: "apple",
        colors: ["black", "red"],
        tags: ["Nokia", "Camera"],
    },
    {
        id: 6,
        name: "Microsoft Surface Laptop Touchscreen 13.5 Inch",
        image: "/images/Deals of The Day product center 1.png",
        alt: "Microsoft Surface Laptop",
        rating: 4,
        reviewCount: 148,
        priceMin: 75.0,
        priceMax: 95.0,
        available: 67,
        isNew: true,
        category: "laptops",
        brand: "dell",
        colors: ["silver", "black"],
        tags: ["Laptop", "Huawei"],
    },
    {
        id: 7,
        name: "OneOdio Wired Over-Ear Studio Headphones",
        image: "/images/Leatest Item (5).png",
        alt: "OneOdio Wired Headphones",
        rating: 3,
        reviewCount: 55,
        priceMin: 22.0,
        priceMax: 32.0,
        available: 420,
        isNew: true,
        category: "gaming",
        brand: "msi",
        colors: ["red", "black"],
        tags: ["Headphone", "Oppo"],
    },
    {
        id: 8,
        name: "Apple iPhone 14 Pro Max 256GB Unlocked",
        image: "/images/Leatest Item (3).png",
        alt: "Apple iPhone 14 Pro Max",
        rating: 5,
        reviewCount: 502,
        priceMin: 89.0,
        priceMax: 110.0,
        available: 54,
        isNew: true,
        category: "tablet",
        brand: "apple",
        colors: ["purple", "black"],
        tags: ["iPhone 13 Pro Max", "iPhone 12"],
    },
    {
        id: 9,
        name: "Smart Watch for Men Women Fitness Tracker",
        image: "/images/bottom_banner_left_product.png",
        alt: "Smart Watch Fitness Tracker",
        rating: 4,
        reviewCount: 201,
        priceMin: 28.0,
        priceMax: 38.0,
        available: 318,
        isNew: true,
        category: "gaming",
        brand: "samsung",
        colors: ["black", "green"],
        tags: ["Symphony", "Samsung"],
    },
    {
        id: 10,
        name: "Bearway Super Console X2 Retro Gaming Handheld",
        image: "/images/buttom_right_product.png",
        alt: "Bearway Super Console X2",
        rating: 4,
        reviewCount: 77,
        priceMin: 35.0,
        priceMax: 45.0,
        available: 190,
        isNew: true,
        category: "gaming",
        brand: "msi",
        colors: ["blue", "black"],
        tags: ["Landing Page", "Nokia"],
    },
    {
        id: 11,
        name: "Microsoft Surface Pro 9 13 Inch Tablet PC",
        image: "/images/Deals of The Day product center 4.png",
        alt: "Microsoft Surface Pro 9",
        rating: 5,
        reviewCount: 266,
        priceMin: 82.0,
        priceMax: 105.0,
        available: 41,
        isNew: true,
        category: "tablet",
        brand: "lenovo",
        colors: ["black", "blue"],
        tags: ["Laptop", "Huawei"],
    },
    {
        id: 12,
        name: "Cloud Cam Wireless Home Security Camera",
        image: "/images/best_seller_product_banner_poset_image.png",
        alt: "Cloud Cam Security Camera",
        rating: 4,
        reviewCount: 119,
        priceMin: 33.0,
        priceMax: 43.0,
        available: 275,
        isNew: true,
        category: "camera",
        brand: "asus",
        colors: ["white", "black"],
        tags: ["Oppo", "Symphony"],
    },
    {
        id: 13,
        name: "Gaming Desktop Tower with RGB Lighting",
        image: "/images/Best Seller Product anather (2).png",
        alt: "Gaming Desktop Tower",
        rating: 4,
        reviewCount: 88,
        priceMin: 70.0,
        priceMax: 98.0,
        available: 33,
        isNew: false,
        category: "desktop",
        brand: "msi",
        colors: ["black", "red"],
        tags: ["Laptop", "Landing Page"],
    },
    {
        id: 14,
        name: "4K Ultra HD Curved Gaming Monitor 32 Inch",
        image: "/images/Best Seller Product anather (3).png",
        alt: "4K Curved Gaming Monitor",
        rating: 5,
        reviewCount: 174,
        priceMin: 58.0,
        priceMax: 78.0,
        available: 96,
        isNew: true,
        category: "monitor",
        brand: "asus",
        colors: ["black"],
        tags: ["Samsung", "Headphone"],
    },
    {
        id: 15,
        name: "Lenovo ThinkPad X1 Carbon Business Laptop",
        image: "/images/top_products (1).png",
        alt: "Lenovo ThinkPad X1 Carbon",
        rating: 5,
        reviewCount: 143,
        priceMin: 85.0,
        priceMax: 108.0,
        available: 29,
        isNew: false,
        category: "laptops",
        brand: "lenovo",
        colors: ["black"],
        tags: ["Laptop", "Huawei"],
    },
    {
        id: 16,
        name: "Wireless Bluetooth Portable Speaker Mini",
        image: "/images/top_products (2).png",
        alt: "Wireless Bluetooth Portable Speaker",
        rating: 3,
        reviewCount: 42,
        priceMin: 18.0,
        priceMax: 26.0,
        available: 510,
        isNew: true,
        category: "gaming",
        brand: "samsung",
        colors: ["blue", "pink", "green"],
        tags: ["Nokia", "Oppo"],
    },
    {
        id: 17,
        name: "Dell UltraSharp USB-C Hub Monitor Dock",
        image: "/images/top_products (3).png",
        alt: "Dell UltraSharp Monitor Dock",
        rating: 4,
        reviewCount: 67,
        priceMin: 42.0,
        priceMax: 56.0,
        available: 112,
        isNew: false,
        category: "monitor",
        brand: "dell",
        colors: ["silver", "black"],
        tags: ["Laptop", "Landing Page"],
    },
    {
        id: 18,
        name: "ASUS ROG Strix Gaming Laptop RTX Edition",
        image: "/images/top_products (4).png",
        alt: "ASUS ROG Strix Gaming Laptop",
        rating: 5,
        reviewCount: 289,
        priceMin: 92.0,
        priceMax: 110.0,
        available: 18,
        isNew: true,
        category: "laptops",
        brand: "asus",
        colors: ["black", "red"],
        tags: ["Laptop", "Samsung"],
    },
];
