import type { LucideIcon } from "lucide-react";
import {
  Airplay,
  AlarmClock,
  Apple,
  Archive,
  Armchair,
  Award,
  Baby,
  Backpack,
  BadgePercent,
  Banknote,
  Bath,
  BatteryCharging,
  BedDouble,
  Beer,
  Bike,
  Bluetooth,
  Bone,
  BookOpen,
  Box,
  BrickWall,
  Briefcase,
  Brush,
  Building2,
  Bus,
  CakeSlice,
  Calculator,
  CalendarDays,
  Camera,
  Car,
  CarFront,
  Cat,
  ChefHat,
  Cherry,
  Cigarette,
  CircuitBoard,
  Clapperboard,
  Clock3,
  CloudSun,
  Coffee,
  Cog,
  Compass,
  Component,
  Cookie,
  Cpu,
  CreditCard,
  Croissant,
  Cross,
  Crown,
  CupSoda,
  Diamond,
  Dog,
  DoorOpen,
  Drama,
  Drill,
  Droplets,
  Dumbbell,
  Ear,
  Egg,
  Eye,
  Factory,
  Fan,
  Feather,
  FerrisWheel,
  Fish,
  Flame,
  FlaskConical,
  Flower2,
  FolderTree,
  Footprints,
  Fuel,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  Glasses,
  Globe2,
  Grape,
  Guitar,
  Hammer,
  HandHeart,
  Headphones,
  Heart,
  HeartPulse,
  Heater,
  Home,
  IceCreamCone,
  Image,
  KeyRound,
  Lamp,
  Landmark,
  Laptop,
  Layers,
  Leaf,
  Lightbulb,
  Lock,
  Luggage,
  Magnet,
  Mail,
  MapPinned,
  Medal,
  Megaphone,
  Mic2,
  Milk,
  Monitor,
  MoonStar,
  Mountain,
  MousePointer2,
  Music2,
  Newspaper,
  Package,
  Paintbrush,
  Palette,
  PawPrint,
  PenTool,
  Percent,
  Phone,
  Piano,
  Pill,
  Pizza,
  Plane,
  Plug,
  Printer,
  Puzzle,
  Radio,
  Refrigerator,
  Ribbon,
  RockingChair,
  Salad,
  Sandwich,
  Scale,
  Scissors,
  ScrollText,
  Server,
  Settings2,
  Shapes,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Smartphone,
  Sofa,
  Soup,
  Sparkles,
  Speaker,
  SprayCan,
  SquarePen,
  Stamp,
  Star,
  Stethoscope,
  Store,
  Sun,
  Sword,
  Syringe,
  Tablet,
  Tag,
  Target,
  Tent,
  Thermometer,
  Ticket,
  Timer,
  Toilet,
  ToolCase,
  ToyBrick,
  TrainFront,
  Trash2,
  TreeDeciduous,
  TreePine,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  UtensilsCrossed,
  Volleyball,
  Wallet,
  WandSparkles,
  Warehouse,
  Watch,
  Waves,
  Wheat,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

export type CategoryIconGroup =
  | "Popular"
  | "Electronics"
  | "Fashion"
  | "Home"
  | "Food"
  | "Health"
  | "Sports"
  | "Pets"
  | "Travel"
  | "Business"
  | "Other";

export type CategoryIconDef = {
  name: string;
  label: string;
  group: CategoryIconGroup;
  Icon: LucideIcon;
};

/** Curated Lucide SVG set for category / product catalog icons (100+). */
export const CATEGORY_ICONS: CategoryIconDef[] = [
  { name: "ShoppingBag", label: "Shopping bag", group: "Popular", Icon: ShoppingBag },
  { name: "ShoppingCart", label: "Cart", group: "Popular", Icon: ShoppingCart },
  { name: "Store", label: "Store", group: "Popular", Icon: Store },
  { name: "Package", label: "Package", group: "Popular", Icon: Package },
  { name: "Tag", label: "Tag", group: "Popular", Icon: Tag },
  { name: "Gift", label: "Gift", group: "Popular", Icon: Gift },
  { name: "Star", label: "Star", group: "Popular", Icon: Star },
  { name: "Sparkles", label: "Sparkles", group: "Popular", Icon: Sparkles },
  { name: "Heart", label: "Heart", group: "Popular", Icon: Heart },
  { name: "Percent", label: "Percent", group: "Popular", Icon: Percent },
  { name: "BadgePercent", label: "Sale badge", group: "Popular", Icon: BadgePercent },
  { name: "FolderTree", label: "Category tree", group: "Popular", Icon: FolderTree },

  { name: "Shirt", label: "Apparel", group: "Fashion", Icon: Shirt },
  { name: "Glasses", label: "Glasses", group: "Fashion", Icon: Glasses },
  { name: "Crown", label: "Luxury", group: "Fashion", Icon: Crown },
  { name: "Watch", label: "Watch", group: "Fashion", Icon: Watch },
  { name: "Gem", label: "Jewelry", group: "Fashion", Icon: Gem },
  { name: "Diamond", label: "Diamond", group: "Fashion", Icon: Diamond },
  { name: "Footprints", label: "Footwear", group: "Fashion", Icon: Footprints },
  { name: "Backpack", label: "Backpack", group: "Fashion", Icon: Backpack },
  { name: "Ribbon", label: "Ribbon", group: "Fashion", Icon: Ribbon },
  { name: "SprayCan", label: "Beauty spray", group: "Fashion", Icon: SprayCan },
  { name: "Brush", label: "Brush", group: "Fashion", Icon: Brush },
  { name: "Palette", label: "Makeup", group: "Fashion", Icon: Palette },
  { name: "WandSparkles", label: "Beauty", group: "Fashion", Icon: WandSparkles },
  { name: "Scissors", label: "Salon", group: "Fashion", Icon: Scissors },

  { name: "Smartphone", label: "Phone", group: "Electronics", Icon: Smartphone },
  { name: "Tablet", label: "Tablet", group: "Electronics", Icon: Tablet },
  { name: "Laptop", label: "Laptop", group: "Electronics", Icon: Laptop },
  { name: "Monitor", label: "Monitor", group: "Electronics", Icon: Monitor },
  { name: "Tv", label: "TV", group: "Electronics", Icon: Tv },
  { name: "Headphones", label: "Headphones", group: "Electronics", Icon: Headphones },
  { name: "Speaker", label: "Speaker", group: "Electronics", Icon: Speaker },
  { name: "Camera", label: "Camera", group: "Electronics", Icon: Camera },
  { name: "Gamepad2", label: "Gaming", group: "Electronics", Icon: Gamepad2 },
  { name: "Cpu", label: "Computer", group: "Electronics", Icon: Cpu },
  { name: "CircuitBoard", label: "Components", group: "Electronics", Icon: CircuitBoard },
  { name: "BatteryCharging", label: "Battery", group: "Electronics", Icon: BatteryCharging },
  { name: "Plug", label: "Power", group: "Electronics", Icon: Plug },
  { name: "Wifi", label: "Network", group: "Electronics", Icon: Wifi },
  { name: "Bluetooth", label: "Bluetooth", group: "Electronics", Icon: Bluetooth },
  { name: "Printer", label: "Printer", group: "Electronics", Icon: Printer },
  { name: "Server", label: "Server", group: "Electronics", Icon: Server },
  { name: "Airplay", label: "Streaming", group: "Electronics", Icon: Airplay },
  { name: "Radio", label: "Radio", group: "Electronics", Icon: Radio },
  { name: "Mic2", label: "Microphone", group: "Electronics", Icon: Mic2 },
  { name: "Zap", label: "Electric", group: "Electronics", Icon: Zap },

  { name: "Home", label: "Home", group: "Home", Icon: Home },
  { name: "Sofa", label: "Furniture", group: "Home", Icon: Sofa },
  { name: "Armchair", label: "Chair", group: "Home", Icon: Armchair },
  { name: "BedDouble", label: "Bedroom", group: "Home", Icon: BedDouble },
  { name: "Lamp", label: "Lighting", group: "Home", Icon: Lamp },
  { name: "Lightbulb", label: "Bulb", group: "Home", Icon: Lightbulb },
  { name: "Fan", label: "Fan", group: "Home", Icon: Fan },
  { name: "Heater", label: "Heater", group: "Home", Icon: Heater },
  { name: "Refrigerator", label: "Appliance", group: "Home", Icon: Refrigerator },
  { name: "Bath", label: "Bathroom", group: "Home", Icon: Bath },
  { name: "ShowerHead", label: "Shower", group: "Home", Icon: ShowerHead },
  { name: "Toilet", label: "Sanitary", group: "Home", Icon: Toilet },
  { name: "DoorOpen", label: "Doors", group: "Home", Icon: DoorOpen },
  { name: "BrickWall", label: "Building", group: "Home", Icon: BrickWall },
  { name: "Hammer", label: "Tools", group: "Home", Icon: Hammer },
  { name: "Wrench", label: "Repair", group: "Home", Icon: Wrench },
  { name: "Drill", label: "Power tools", group: "Home", Icon: Drill },
  { name: "Shovel", label: "Garden", group: "Home", Icon: Shovel },
  { name: "Flower2", label: "Plants", group: "Home", Icon: Flower2 },
  { name: "TreeDeciduous", label: "Outdoor", group: "Home", Icon: TreeDeciduous },
  { name: "TreePine", label: "Trees", group: "Home", Icon: TreePine },
  { name: "Droplets", label: "Water", group: "Home", Icon: Droplets },
  { name: "Paintbrush", label: "Paint", group: "Home", Icon: Paintbrush },
  { name: "RockingChair", label: "Living", group: "Home", Icon: RockingChair },

  { name: "UtensilsCrossed", label: "Dining", group: "Food", Icon: UtensilsCrossed },
  { name: "Coffee", label: "Coffee", group: "Food", Icon: Coffee },
  { name: "CupSoda", label: "Drinks", group: "Food", Icon: CupSoda },
  { name: "Wine", label: "Wine", group: "Food", Icon: Wine },
  { name: "Beer", label: "Beer", group: "Food", Icon: Beer },
  { name: "Pizza", label: "Pizza", group: "Food", Icon: Pizza },
  { name: "Sandwich", label: "Sandwich", group: "Food", Icon: Sandwich },
  { name: "Soup", label: "Soup", group: "Food", Icon: Soup },
  { name: "Salad", label: "Salad", group: "Food", Icon: Salad },
  { name: "CakeSlice", label: "Bakery", group: "Food", Icon: CakeSlice },
  { name: "Croissant", label: "Pastry", group: "Food", Icon: Croissant },
  { name: "Cookie", label: "Snacks", group: "Food", Icon: Cookie },
  { name: "IceCreamCone", label: "Dessert", group: "Food", Icon: IceCreamCone },
  { name: "Apple", label: "Fruit", group: "Food", Icon: Apple },
  { name: "Cherry", label: "Berries", group: "Food", Icon: Cherry },
  { name: "Grape", label: "Grapes", group: "Food", Icon: Grape },
  { name: "Wheat", label: "Grains", group: "Food", Icon: Wheat },
  { name: "Milk", label: "Dairy", group: "Food", Icon: Milk },
  { name: "Egg", label: "Eggs", group: "Food", Icon: Egg },
  { name: "Fish", label: "Seafood", group: "Food", Icon: Fish },
  { name: "ChefHat", label: "Kitchen", group: "Food", Icon: ChefHat },

  { name: "HeartPulse", label: "Health", group: "Health", Icon: HeartPulse },
  { name: "Stethoscope", label: "Medical", group: "Health", Icon: Stethoscope },
  { name: "Pill", label: "Pharmacy", group: "Health", Icon: Pill },
  { name: "Syringe", label: "Clinic", group: "Health", Icon: Syringe },
  { name: "Cross", label: "First aid", group: "Health", Icon: Cross },
  { name: "Thermometer", label: "Thermometer", group: "Health", Icon: Thermometer },
  { name: "FlaskConical", label: "Lab", group: "Health", Icon: FlaskConical },
  { name: "Eye", label: "Vision", group: "Health", Icon: Eye },
  { name: "Ear", label: "Hearing", group: "Health", Icon: Ear },
  { name: "Baby", label: "Baby care", group: "Health", Icon: Baby },
  { name: "HandHeart", label: "Wellness", group: "Health", Icon: HandHeart },
  { name: "Leaf", label: "Organic", group: "Health", Icon: Leaf },
  { name: "Flame", label: "Energy", group: "Health", Icon: Flame },

  { name: "Dumbbell", label: "Fitness", group: "Sports", Icon: Dumbbell },
  { name: "Bike", label: "Cycling", group: "Sports", Icon: Bike },
  { name: "Volleyball", label: "Sports ball", group: "Sports", Icon: Volleyball },
  { name: "Trophy", label: "Trophy", group: "Sports", Icon: Trophy },
  { name: "Medal", label: "Medal", group: "Sports", Icon: Medal },
  { name: "Award", label: "Award", group: "Sports", Icon: Award },
  { name: "Target", label: "Target", group: "Sports", Icon: Target },
  { name: "Timer", label: "Timer", group: "Sports", Icon: Timer },
  { name: "Gauge", label: "Performance", group: "Sports", Icon: Gauge },
  { name: "Sword", label: "Combat sports", group: "Sports", Icon: Sword },
  { name: "Tent", label: "Camping", group: "Sports", Icon: Tent },
  { name: "Mountain", label: "Hiking", group: "Sports", Icon: Mountain },
  { name: "Waves", label: "Water sports", group: "Sports", Icon: Waves },
  { name: "FerrisWheel", label: "Recreation", group: "Sports", Icon: FerrisWheel },

  { name: "PawPrint", label: "Pets", group: "Pets", Icon: PawPrint },
  { name: "Dog", label: "Dogs", group: "Pets", Icon: Dog },
  { name: "Cat", label: "Cats", group: "Pets", Icon: Cat },
  { name: "Bone", label: "Pet food", group: "Pets", Icon: Bone },

  { name: "Plane", label: "Flights", group: "Travel", Icon: Plane },
  { name: "Car", label: "Cars", group: "Travel", Icon: Car },
  { name: "CarFront", label: "Vehicles", group: "Travel", Icon: CarFront },
  { name: "Bus", label: "Bus", group: "Travel", Icon: Bus },
  { name: "TrainFront", label: "Train", group: "Travel", Icon: TrainFront },
  { name: "Truck", label: "Shipping", group: "Travel", Icon: Truck },
  { name: "Fuel", label: "Fuel", group: "Travel", Icon: Fuel },
  { name: "Luggage", label: "Luggage", group: "Travel", Icon: Luggage },
  { name: "MapPinned", label: "Location", group: "Travel", Icon: MapPinned },
  { name: "Compass", label: "Compass", group: "Travel", Icon: Compass },
  { name: "Globe2", label: "World", group: "Travel", Icon: Globe2 },
  { name: "Ticket", label: "Tickets", group: "Travel", Icon: Ticket },
  { name: "Umbrella", label: "Umbrella", group: "Travel", Icon: Umbrella },
  { name: "Sun", label: "Beach", group: "Travel", Icon: Sun },
  { name: "CloudSun", label: "Weather", group: "Travel", Icon: CloudSun },
  { name: "MoonStar", label: "Night", group: "Travel", Icon: MoonStar },

  { name: "Briefcase", label: "Office", group: "Business", Icon: Briefcase },
  { name: "Building2", label: "Company", group: "Business", Icon: Building2 },
  { name: "Landmark", label: "Bank", group: "Business", Icon: Landmark },
  { name: "Wallet", label: "Wallet", group: "Business", Icon: Wallet },
  { name: "CreditCard", label: "Payments", group: "Business", Icon: CreditCard },
  { name: "Banknote", label: "Cash", group: "Business", Icon: Banknote },
  { name: "Calculator", label: "Accounting", group: "Business", Icon: Calculator },
  { name: "Scale", label: "Legal", group: "Business", Icon: Scale },
  { name: "Lock", label: "Security", group: "Business", Icon: Lock },
  { name: "Shield", label: "Protection", group: "Business", Icon: Shield },
  { name: "KeyRound", label: "Access", group: "Business", Icon: KeyRound },
  { name: "Mail", label: "Mail", group: "Business", Icon: Mail },
  { name: "Phone", label: "Contact", group: "Business", Icon: Phone },
  { name: "Megaphone", label: "Marketing", group: "Business", Icon: Megaphone },
  { name: "Newspaper", label: "News", group: "Business", Icon: Newspaper },
  { name: "CalendarDays", label: "Events", group: "Business", Icon: CalendarDays },
  { name: "AlarmClock", label: "Alarms", group: "Business", Icon: AlarmClock },
  { name: "Clock3", label: "Time", group: "Business", Icon: Clock3 },
  { name: "Factory", label: "Industry", group: "Business", Icon: Factory },
  { name: "Warehouse", label: "Warehouse", group: "Business", Icon: Warehouse },
  { name: "Settings2", label: "Settings", group: "Business", Icon: Settings2 },
  { name: "Cog", label: "Config", group: "Business", Icon: Cog },

  { name: "BookOpen", label: "Books", group: "Other", Icon: BookOpen },
  { name: "ScrollText", label: "Documents", group: "Other", Icon: ScrollText },
  { name: "SquarePen", label: "Stationery", group: "Other", Icon: SquarePen },
  { name: "PenTool", label: "Design", group: "Other", Icon: PenTool },
  { name: "Music2", label: "Music", group: "Other", Icon: Music2 },
  { name: "Piano", label: "Instruments", group: "Other", Icon: Piano },
  { name: "Guitar", label: "Guitar", group: "Other", Icon: Guitar },
  { name: "Clapperboard", label: "Movies", group: "Other", Icon: Clapperboard },
  { name: "Drama", label: "Theater", group: "Other", Icon: Drama },
  { name: "ToyBrick", label: "Toys", group: "Other", Icon: ToyBrick },
  { name: "Puzzle", label: "Games", group: "Other", Icon: Puzzle },
  { name: "Shapes", label: "Shapes", group: "Other", Icon: Shapes },
  { name: "Layers", label: "Layers", group: "Other", Icon: Layers },
  { name: "Component", label: "Parts", group: "Other", Icon: Component },
  { name: "Box", label: "Box", group: "Other", Icon: Box },
  { name: "Archive", label: "Archive", group: "Other", Icon: Archive },
  { name: "Image", label: "Photos", group: "Other", Icon: Image },
  { name: "Feather", label: "Craft", group: "Other", Icon: Feather },
  { name: "Stamp", label: "Stamps", group: "Other", Icon: Stamp },
  { name: "Magnet", label: "Magnet", group: "Other", Icon: Magnet },
  { name: "Trash2", label: "Cleaning", group: "Other", Icon: Trash2 },
  { name: "Cigarette", label: "Tobacco", group: "Other", Icon: Cigarette },
  { name: "ToolCase", label: "Toolkit", group: "Other", Icon: ToolCase },
  { name: "MousePointer2", label: "Digital", group: "Other", Icon: MousePointer2 },
];

export const CATEGORY_ICON_GROUPS: CategoryIconGroup[] = [
  "Popular",
  "Electronics",
  "Fashion",
  "Home",
  "Food",
  "Health",
  "Sports",
  "Pets",
  "Travel",
  "Business",
  "Other",
];

const iconMap = new Map(CATEGORY_ICONS.map((item) => [item.name, item]));

export function resolveCategoryIcon(
  name: string | null | undefined,
): CategoryIconDef {
  if (name && iconMap.has(name)) return iconMap.get(name)!;
  return iconMap.get("FolderTree")!;
}

export function getCategoryLucideIcon(
  name: string | null | undefined,
): LucideIcon {
  return resolveCategoryIcon(name).Icon;
}
